### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by iamRjarpan** [gwen001/DataExtractor#2]
Hi I really love this tool. But is it possible to add options like "Send to DataExtrator" so I can spicificly can resend old endpoints that I dont want to revisit.

**Comment by gwen001** [comment]
That option is not really needed imho as the extension works as a passive scan. So you just need to select the items you want to parse again, right click and choose "Do a passive scan".

I bind it on Ctrl+Shift+S

**Comment by iamRjarpan** [comment]
Okey I got it. Thanks @gwen001
